name: Build and Test 

on: 
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        services:
         statsd:
          image: statsd/statsd
          ports:
            - 8127:8127/udp
         statsite:
          image: quay.io/prometheus/statsd-exporter
          ports:
            - 8126:8126

        steps:
            - name: Checkout Code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
            - name: Setup Go
              uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a
              with:
                go-version: '1.18'
            - name: Test Go
              run: |
                for dir in $(find . -name "go.mod" -exec dirname {} \;); do
                  echo "Running tests in module $dir"
                  (cd $dir && go test -v ./...)
                done
            - name: Build Go
              run: |
                for dir in $(find . -name "go.mod" -exec dirname {} \;); do
                  echo "Running build in module $dir"
                  (cd $dir && go build -v ./...)
                done