name: Build and Test 

on: 
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        services:
         statsd:
          image: statsd/statsd
          ports:
            - 8125:8125/udp
         statsite:
          image: quay.io/prometheus/statsd-exporter
          ports:
            - 7523:7523

        steps:
            - name: Checkout Code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
            - name: Setup Go
              uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a
              with:
                go-version: '1.18'
            - name: Debug active processes
              run: |
                    sudo lsof -i
                    go mod tidy
            - name: Build Go
              run: go build ./...
            - name: Run Tests
              run: go test ./...
