name: Build and Test 

on: 
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
            - name: Setup Go
              uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a
              with:
                go-version: '1.12'
            - run: go build ./...